<?php
/******************************************************************
* Copyright © 2012 ICT Innovations Pakistan All Rights Reserved   *
* Developed By: Falak Nawaz                                       *
*             : Nasir Iqbal                                       *
*             : Tahir Almas                                       *
* Website : http://www.ictinnovations.com/                        *
* Mail : info@ictinnovations.com                                  *
******************************************************************/
/**
* Sending FAX Module
* Conversion to Drupal 7x
* 23 Feb 2012
*/

/**
* Display help and module information
* @param section which section of the site we're displaying help
* @return help text for section
*/

function ictfax_help($section='') {
  $output = '';
  switch ($section) {
    case "admin/modules#description":
      $output = t("ICTBilling Fax Account");
      break;
  }
  return $output;
} // function ictfax_help


function ictfax_menu() {
  $items = array();

  $items['ictfax'] = array(
    'title'            => t('Fax Account'),
    'description'      => 'Fax Account',
    'page callback'    => 'system_admin_menu_block_page',
    'file'             => 'system.admin.inc',
    'file path'        => drupal_get_path('module', 'system'),
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'position'         => 'left',
    'expanded'         => TRUE,
    'weight'           => -10,
  );

  $items['ictfax/outbox'] = array(
    'title'            => t('Fax Outbox'),
    'description'      => 'Fax Outbox',
    'page callback'    => 'ictfax_outbox_list',
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type'             => MENU_NORMAL_ITEM,
    'weight'           => 10,
  );  

  $items['ictfax/outbox/list'] = array(
    'title'            => t('List'),
    'description'      => 'Fax Outbox',
    'page callback'    => 'ictfax_outbox_list',
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'weight'           => 10,
  );

  // shows form to add new
  $items['ictfax/outbox/add'] = array(
    'title'            => t('Create new Fax'),
    'description'      => 'Creates a new Fax',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('ictfax_form', array()),
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type'             => MENU_LOCAL_TASK,
    'weight'           => 11,
  );

  $items['ictfax/outbox/%ictfax/edit'] = array(
    'title'            => t('Edit Fax'),
    'description'      => 'Edit Fax',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('ictfax_form', 2),
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type' => MENU_CALLBACK,
  );

  $items['ictfax/outbox/%ictfax/delete'] = array(
    'title'            => t('Delete Fax'),
    'description'      => 'Delete Fax',
    'page callback'    => 'ictfax_delete',
    'page arguments'   => array(2),
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type' => MENU_CALLBACK,
  );

  $items['ictfax/outbox/%ictfax/resend'] = array(
    'title'            => t('Resend Fax'),
    'description'      => 'Resend Fax',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('ictfax_resend', 1),
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type' => MENU_CALLBACK,
    //'weight' => -10,
  );

  $items['ictfax/outbox/%ictfax/view'] = array(
    'title'            => t('View Fax'),
    'description'      => 'View Fax',
    'page callback'    => 'ictfax_view',
    'page arguments'   => array(1),
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type' => MENU_CALLBACK,
    //'weight' => -10,
  );

  $items['ictfax/outbox/%ictfax/download'] = array(
    'title'            => t('Download Fax'),
    'description'      => 'Download Fax',
    'page callback'    => 'ictfax_download',
    'page arguments'   => array(1),
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type' => MENU_CALLBACK,
    //'weight' => -10,
  );

  $items['ictfax/inbox'] = array(
    'title'            => t('Fax Inbox'),
    'description'      => 'Fax Inbox',
    'page callback'    => 'ictfax_inbox_list',
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type'             => MENU_NORMAL_ITEM,
    'weight'           => 11,
  );

  $items['ictfax/inbox/list'] = array(
    'title'            => t('List'),
    'description'      => 'Fax Inbox',
    'page callback'    => 'ictfax_inbox_list',
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type'             => MENU_DEFAULT_LOCAL_TASK,
    'weight'           => 11,
  );

  $items['ictfax/inbox/%ictfax/delete'] = array(
    'title'            => t('Delete Fax'),
    'description'      => 'Delete Fax',
    'page callback'    => 'ictfax_delete',
    'page arguments'   => array(2),
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type' => MENU_CALLBACK,
  );

  $items['ictfax/inbox/%ictfax/view'] = array(
    'title'            => t('View Fax'),
    'description'      => 'View Fax',
    'page callback'    => 'ictfax_view',
    'page arguments'   => array(1),
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type' => MENU_CALLBACK,
    //'weight' => -10,
  );

  $items['ictfax/inbox/%ictfax/download'] = array(
    'title'            => t('Download Fax'),
    'description'      => 'Download Fax',
    'page callback'    => 'ictfax_download',
    'page arguments'   => array(1),
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type' => MENU_CALLBACK,
    //'weight' => -10,
  );

  $items['ictfax/phonebookpopup'] = array(
    'title'            => t('Phonebook Popup'),
    'description'      => 'Phonebook Popup',
    'page callback'    => 'ictfax_popup',
//    'page arguments'   => array('ictfax_list_contacts'),    
    'access callback'  => 'ictfax_access',
    'access arguments' => array('can use ictfax'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implementation of hook_node_name
 */
function ictfax_node_name() {
  $name = t('Fax Account');
  if ( empty($name) ) {
    $name = 'Fax Account';
  }
  return $name;
}

/**
* Valid permissions for this module
* @return array An array of valid permissions for the ictfax module
* At this point, we'll give permission to anyone who can access site content 
* or administrate the module:
*/
function ictfax_permission() {
  return array(
    'can use ictfax'  => array('title'=> 'can use ictfax'),
  );
}

function ictfax_access($access) {
  global $user;
  if (is_array($access)) $access = $access[0];
  if (!user_access($access)) return false;
  return true;
}

/**
 * This function creates a list of faxs for the specified interface
 */
function ictfax_outbox_list() {
  global $user;

  include_once "/usr/ictcore/core/core.php";

  // first of all load user in ict framework
  /*$listUser = User::search(array('created_by' => $user->uid));
  $aUser    = array_shift($listUser);
  do_login($aUser['user_id']); */
  do_login($user->uid);

  $service_flag = Fax::SERVICE_FLAG;
  $header = array(
    array('data' => t('Job ID'),    'field' => 'transmission_id', 'sort' => 'desc'),
    array('data' => t('Fax From'),  'field' => 'account_id'),
    array('data' => t('Fax To'),    'field' => 'contact_id'),
    array('data' => t('Status'),    'field' => 'status'),
    array('data' => t('Result'),    'field' => ''),
    array('data' => t('Action'),    'field' => ''),
  );

  $query = CoreDB::db_select('transmission', 't')->extend('PagerDefault');
  $query->fields('t', array('transmission_id', 'account_id', 'contact_id', 'status'));
  $query->leftjoin('account','a','a.account_id = t.account_id');
  $query->leftjoin('usr','u','u.usr_id = a.created_by');
  $query->condition('u.usr_id', $user->uid , '=');
  $query->condition('t.direction', 'outbound', '=');
  $query->condition('t.service_flag', $service_flag, '=');
  $result = $query->limit(50)         
            ->extend('TableSort')
            ->orderByHeader($header)
            ->execute();
  while ($transmission = $result->fetchAssoc()) {
    $row_id   = $transmission['transmission_id'];
    $spool_id = ictfax_get_spool_id($transmission['transmission_id']);
    $rows[$row_id][] = check_plain($transmission['transmission_id']);
    $rows[$row_id][] = check_plain(ictfax_get_account_name($transmission['account_id']));  // from 
    $rows[$row_id][] = check_plain(ictfax_get_contact_name($transmission['contact_id']));  // to
    $rows[$row_id][] = check_plain($transmission['status']);
    $rows[$row_id][] = check_plain(ictfax_get_fax_result($spool_id));    // fax result
    $rows[$row_id][] = _ictfax_list_links($transmission);
  }
  if (!isset($rows)) {
    $rows[] = array(array('data' => t('No faxes have been created to send.'), 'colspan' => 8));
  }
  $output = theme('table', array('header'=>$header, 'rows'=>$rows));
  $output .= theme('pager');

  if (!isset($_SESSION['fax_status']) || $_SESSION['fax_status'] == 'in_queue') {
    $output .= ictfax_getJaveScript();
  }
 
  return $output;
}

function _ictfax_list_links($transmission) {
  /*$links['edit'] = array(
    'title' => t('Edit'),
    'href' => 'ictfax/outbox/' . $transmission['cid'] . '/edit',
    'html' => TRUE,
  );*/
  $links['delete'] = array(
    'title' => t('Delete'),
    'href' => 'ictfax/outbox/' . $transmission['transmission_id'] . '/delete',
    'html' => TRUE,
  );
  return theme('links', array('links'=>$links, 'attributes' => array('class' => array('links', 'inline'))));
}

/**
 * This function creates a list of incomming faxs
 */
function ictfax_inbox_list() {
  global $user;

  $service_flag = 2; // Fax::SERVICE_FLAG
  $header = array(
    array('data' => t('Job ID'),    'field' => 'transmission_id', 'sort' => 'desc'),
    array('data' => t('Fax From'),  'field' => 'contact_id'),
    array('data' => t('Fax To'),    'field' => 'account_id'),
    array('data' => t('Status'),    'field' => 'status'),
    array('data' => t('Result'),    'field' => ''),
    array('data' => t('Action'),    'field' => ''),
  );

  $query = CoreDB::db_select('transmission', 't')->extend('PagerDefault');
  $query->fields('t', array('transmission_id', 'contact_id', 'account_id', 'status'));
  $query->leftjoin('account','a','a.account_id = t.account_id');
  $query->leftjoin('usr','u','u.usr_id = a.created_by');
  $query->condition('u.usr_id', $user->uid , '=');
  $query->condition('t.direction', 'inbound','=');
  $query->condition('t.service_flag', $service_flag,'=');
  $result = $query->limit(50)         
            ->extend('TableSort')
            ->orderByHeader($header)
            ->execute();
  while ($transmission = $result->fetchAssoc()) {
    $row_id   = $transmission['transmission_id']; 
    $spool_id = ictfax_get_spool_id($transmission['transmission_id']);
    $rows[$row_id][] = check_plain($transmission['transmission_id']);
    $rows[$row_id][] = check_plain(ictfax_get_contact_name($transmission['contact_id']));
    $rows[$row_id][] = check_plain(ictfax_get_account_name($transmission['account_id']));
    $rows[$row_id][] = check_plain($transmission['status']);
    $rows[$row_id][] = check_plain(ictfax_get_fax_result($spool_id));    // fax result
    $rows[$row_id][] = _ictfax_list_links($transmission);
  }
  if (!isset($rows)) {
    $rows[] = array(array('data' => t('No faxes have been received.'), 'colspan' => 8));
  }
  $output = theme('table', array('header'=>$header, 'rows'=>$rows));
  $output .= theme('pager');

  if (!isset($_SESSION['fax_status']) || $_SESSION['fax_status'] == 'in_queue') {
    $output .= ictfax_getJaveScript();
  }

  return $output;
}

function ictfax_get_spool_id($transmission_id) {
  $query    = "SELECT s.spool_id FROM spool s WHERE s.transmission_id = :transmission_id ORDER BY s.spool_id DESC LIMIT 1";
  $query_rs = CoreDB::db_query($query, array(':transmission_id' => $transmission_id));
  $spool    = $query_rs->fetchAssoc();
  return $spool['spool_id'];
}

function ictfax_get_fax_result($spool_id) {
  $query    = "SELECT sr.data FROM spool_result sr WHERE sr.name IN ('fax_send','fax_receive') AND sr.spool_id = :spool_id";
  $query_rs = CoreDB::db_query($query, array(':spool_id' => $spool_id));
  $result   = $query_rs->fetchAssoc();
  return !empty($result['data']) ? $result['data'] : '-';
}

function ictfax_get_message_filename($spool_id){
  $query    = "SELECT sr.data FROM spool_result sr WHERE sr.type = 'document' AND sr.spool_id = :spool_id";
  $query_rs = CoreDB::db_query($query, array(':spool_id' => $spool_id));
  $result   = $query_rs->fetchAssoc();
  $oDocument= new Document($result['data']);
  return $oDocument->file_name;
}

function ictfax_get_account_name($account_id){
  //$query    = 'SELECT CONCAT(first_name, last_name) AS name FROM account WHERE account_id = :account_id';
  $query    = 'SELECT phone FROM account WHERE account_id = :account_id';
  $query_rs = CoreDB::db_query($query, array(':account_id' => $account_id));
  $account  = $query_rs->fetchAssoc();
  return $account['phone'];
} 

function ictfax_get_contact_name($contact_id){
  //$query    = 'SELECT CONCAT(first_name, last_name) AS name FROM contact WHERE contact_id = :contact_id';
  $query    = 'SELECT phone FROM contact WHERE contact_id = :contact_id';
  $query_rs = CoreDB::db_query($query, array(':contact_id' => $contact_id));
  $contact  = $query_rs->fetchAssoc(); 
  return $contact['phone'];
} 

function _ictfax_list_incoming_links($transmission) {
  $links['delete'] = array(
    'title' => t('Delete'),
    'href' => 'ictfax/inbox/' . $transmission['transmission_id'] . '/delete',
    'html' => TRUE,
  );
  if (!empty($transmission['message_id'])) {
    $links['view'] = array(
      'title' => t('View'),
      'href'  => 'ictfax/'.$transmission['message_id'].'/view',
      'html'  => TRUE,
    );
  }
  return theme('links', array('links'=>$links, 'attributes' => array('class' => array('links', 'inline'))));
}

/**
 * Display / Download fax document
 */

function ictfax_message_load($message_id) {
  global $user;
  if($cid != null) {
    $query  = 'SELECT * FROM document WHERE document_id = :document_id AND created_by=:created_by';
    $result = CoreDB::db_query($query, array(':document_id' => $message_id, ':created_by' => $user->uid));
    if ($document = $result->fetchAssoc()) {
      return $document;
    }
    else {
      drupal_set_message(t('Specified Fax does not exist! or you have not proper permissions!'), 'error');
      return FALSE;
    }
  }
}

function ictfax_view($message) {
  
}

function ictfax_download($message) {
  
}

/**
 * Loads a fax
 */
function ictfax_load($transmission_id) {
  global $user;
  if ($transmission_id != null) {
    $query  = 'SELECT * FROM transmission WHERE transmission_id = :transmission_id AND created_by=:created_by';
    $result = CoreDB::db_query($query, array(':transmission_id' => $transmission_id, ':created_by' => $user->uid));
    if ($transmission = $result->fetchAssoc()) {
      return $transmission;
    } else {
      drupal_set_message(t('Specified Fax does not exist! or you have not proper permissions!'), 'error');
      return FALSE;
    }
  }
}

/**
 * Crates a input form
 */
function ictfax_form($form, &$form_state, $edit = array()) {
  $edit += array(
    'send_to'    => '',
    'send_from'  => '',
    'text'       => '',
    'file_name'  => '',
    'try_max'    => 1,
  );

  // Include the CTools tools that we need.
  ctools_include('ajax');
  ctools_include('modal');
  // Add CTools' javascript to the page.
  ctools_modal_add_js();
//  drupal_add_js(drupal_get_path('module', 'ictfax') . '/fax_answer.js');
  // If we're editing an existing fax, we'll add a value field to the form
  // containing the fax's unique ID.
  if (!empty($edit['cid'])) {
    $form['cid'] = array(
      '#type'        => 'value',
      '#value'       => $edit['cid'],
    );
  }

  $form['info'] = array(
    '#type'          => 'fieldset',
    '#title'         => t('Fax Information'),
  );

  $form['info']['send_to'] = array(
    '#type'          => 'textfield',
    '#title'         => t('Send To'),
    '#required'      => TRUE,
    '#size'          => 60, 
    '#maxlength'     => 128, 
    '#description' => t('Click \'Phonebook\' to select fax #. where to send fax'),
    '#default_value' => $edit['send_to'],
  );
  
  $form['info']['url'] = array(
    '#type' => 'hidden',
    // The name of the class is the #id of $form['ajax_button'] with "-url"
    // suffix.
    '#attributes' => array('class' => array('contact-button-url')),
    '#value' => url('ictfax/phonebookpopup'),    
  );
  
  $form['info']['ajax_button'] = array(
    '#type' => 'button',
    '#value' => 'Phonebook',
    '#attributes' => array('class' => array('ctools-use-modal')),
    '#id' => 'contact-button',
  );

  $form['info']['text'] = array(
    '#type'          => 'hidden',
    '#title'         => t('Message'),
    '#required'      => FALSE,
    '#cols'          => 60, 
    '#rows'          => 10,
    '#default_value' => $edit['text'],
  );
  
  // helper field for file upload
  $form['#attributes'] = array('enctype' => "multipart/form-data");
  $form['info']['file_name'] = array(
    '#type'          => 'file',
    '#title'         => t('Fax file'),
    '#required'      => FALSE,
    '#description'   => t('Select a file to send as fax, please use only tif, pdf, jpg, png, gif or txt file'),
  );

  $form['info']['try_max'] = array(
    '#type'          => 'select',
    '#title'         => t('No. of Retries'),
    '#options'       => array(
       1 => t('[None]'), // no retry = 1 try
       2 => t('1'),          // 1 retry  = 2 tries and so on ...
       3 => t('2'), 
       4 => t('3')),
    '#description'   => t('No. of tries if call failed'),
    '#default_value' => $edit['try_max'],
  );

  $form['submit'] = array(
    '#type'          => 'submit',
    '#value'         => t('Create new Fax'),
  );
  
  return $form;
}

/**
 * Performs validation.
 *
 */ 
 function ictfax_form_validate($form, &$form_state) {
  $transmission = $form_state['values'];
  if (isset($transmission['transmission_id'])) {
    // we are editing an existing record
    $existing_record = $transmission['transmission_id'];
  }
  if ($transmission['send_to'] == '') {
    form_set_error('send_to', t('Recipient cannot be empty'));
  }
  if (empty($transmission['send_to'])) {
    form_set_error('send_to', t('Fax Number is required.'));
  } else {
    if (!ctype_digit(str_replace(array('+', ','), '',$transmission['send_to']))) {
        form_set_error('send_to', t('Fax Number is not valid.'));
    }
  }
  // Validate file
  $allowedTypes = array(
     1=>'odt',  2=>'ott',  3=>'sxw',  4=>'stw',  5=>'doc',  6=>'dot',  7=>'sdw',  8=>'vor',  9=>'htm', 10=>'sdd', 
    11=>'sdp', 12=>'wpd', 13=>'ods', 14=>'ots', 15=>'sxc', 16=>'stc', 17=>'xls', 18=>'xlw', 19=>'xlt', 20=>'sdc', 
    21=>'csv', 22=>'odp', 23=>'otp', 24=>'sxi', 25=>'sti', 26=>'ppt', 27=>'pps', 28=>'pot', 29=>'sxd', 30=>'odt', 
    31=>'ott', 32=>'sxw', 33=>'stw', 34=>'doc', 35=>'dot', 36=>'sdw', 37=>'vor', 38=>'htm', 39=>'sdd', 40=>'sdp', 
    41=>'wpd', 42=>'ods', 43=>'ots', 44=>'sxc', 45=>'stc', 46=>'xls', 47=>'xlw', 48=>'xlt', 49=>'sdc', 50=>'csv', 
    51=>'odp', 52=>'otp', 53=>'sxi', 54=>'sti', 55=>'ppt', 56=>'pps', 57=>'pot', 58=>'sxd', 59=>'txt', 60=>'tif', 
    61=>'jpg', 62=>'pdf', 63=>'png', 64=>'gif',
  );
  $validators = array('file_validate_extensions' => $allowedTypes);
  $file = file_save_upload('file_name', $validators);
  if ($file) {
    $form_state['values']['file_name'] = $file; // drupal file object
  } else {
    form_set_error('file_name', "File is required");
  }
}

 /**
 * Persist the changes to the database
 */
function ictfax_form_submit($form, &$form_state) {
  global $user;

  include_once "/usr/ictcore/core/core.php";

  // first of all load user in ict framework
  /*$listUser = User::search(array('created_by' => $user->uid));
  $aUser    = array_shift($listUser);
  do_login($aUser['user_id']); */
  do_login($user->uid);

  $data = $form_state['values'];

  $oDocument = new Document();
  $oDocument->name = random;
  if (!empty($data['file_name']->uri)) {
    $oDocument->file_name = drupal_realpath($data['file_name']->uri);
  } else {
    $oDocument->text = $data['text'];
  }
  $oDocument->save();

  // prepare program data
  $programData = array(
    'data' => array(
      'document_id' => $oDocument->document_id
    )
  );
  // prepare transmission data
  $transmissionData = array(
    'phone'       => $data['send_to'],
    'try_allowed' => $data['try_max'],
    'origin'      => 'web'
  );
  $faxTransmission = Sendfax::transmission_instant($programData, $transmissionData);
  $faxTransmission->send();

  drupal_set_message(t('FAX uploaded successfully!'), 'info');
  $form_state['redirect'] = 'ictfax/outbox/list';
  return true;
}

/**
 * Deletes a recording, given its unique ID.
 *
 * @param $recording
 *   An array of recording containing the ID of a recording
 */
function ictfax_delete($transmission) {
  include_once "/usr/ictcore/core/core.php";

  $oTransmission = new Transmission($transmission['transmission_id']);
  if ($oTransmission->delete()) {
    drupal_set_message(t('Fax deleted successfully!'), 'status');
  } else {
    drupal_set_message(t('Cannot delete specified fax! fax does not exist or you have not proper permissions!'), 'error');
  }
  drupal_goto('ictfax/outbox');
}

function ictfax_getPhoneNo($item, $key)
{
    $item = str_replace(array('-','_',' '),'',$item);
}

function ictfax_onload() {
  if (isset($_SESSION['fax_status']) && $_SESSION['fax_status'] == 'in_queue') {
      return array('setTimer()');   
  }
} 


function ictfax_getJaveScript() {
   $myjava = '
<script language="JavaScript">
var msgIX = 0
   
function setTimer() {
    window.setInterval("displayMessage()", 3000)
}

function displayMessage() {
  try {
    p = new XMLHttpRequest();
  } catch (e) {
    p = new ActiveXObject("Msxml2.XMLHTTP");
  }
  var interactiveCount = 0;
  // p.onload would also work in Mozilla
  p.onreadystatechange = FaxStatus;
  try {
    // Needed for Mozilla if local file tries to access an http URL
    netscape.security.PrivilegeManager.enablePrivilege("UniversalBrowserRead");
  } catch (e) {
    // ignore
  }
  postq = "q=ictfax/getfaxstatus&tt=" + Math.random();
  p.open("GET", "?" + postq);
  p.send(postq);
}

function FaxStatus()
{
  if (p.readyState != 4)
    return;
  var myresp = p.responseText;
  var myresp_line=myresp.split("\n");
  var myresp_array=myresp_line[0].split("|");
    var loop_ct = 1;

  document.getElementById("faxstatus").innerHTML = p.responseText;
}

</script>
';
    return $myjava;
}

function ictfax_getfaxstatus() {
  global $user;
  $aCid = $_SESSION['fax_cid'];
  $output = '';
  foreach ($aCid as $key => $transmission_id) {
    $query  = "SELECT contact_id, status, response FROM transmission 
               WHERE transmission_id = :transmission_id AND created_by = :created_by";
    $tranRs = CoreDB::db_query($query, array(':transmission_id' => $transmission_id, ':created_by' => $user->uid));
    $transmission = $tranRs->fetchObject();
    if ($transmission->status == 'failed') {
      $color = "ff0000"; // red
    } elseif ($transmission->status == 'completed') {
      $color = "00ff00"; // green
    } else { // in queue, initiated etc ...
      $color = "0000ff"; // blue
    }
    $output  = '<font color="#000">Sending FAX to '.$transmission->contact_id.' stutus is:&nbsp;</font>';
    $output .= '<font color="#'.$color.'">'.$transmission->status.'</font>';
  }
  return $output;
}

function ictfax_popup() {

  ctools_include('ajax');
  ctools_include('modal');
  
  //ctools_include('form');
  // Have to do this or form submit won't work right.
  //drupal_add_js('misc/jquery.form.js');
  //ctools_add_js('ajax-responder');
  
  $form_state = array(
    'ajax' => TRUE,
    'title' => t('Phonebook'),
  );
  $output = ctools_modal_form_wrapper('ictfax_list_contacts', $form_state, array());
  //$output = ctools_build_form('ictfax_list_contacts', $form_state, array());
  
  if (isset($form_state['complete'])) {
    //$output[] = ctools_ajax_command_replace('#modal-complete', '<div id="modal-complete">' . $form_state['values']['#edit-send-to']['value'] . '</div>');
    $animal = '<div class="form-item form-type-textfield form-item-send-to">
      <label for="edit-send-to">Send To <span class="form-required" title="This field is required.">*</span></label>
      <input type="text" id="edit-send-to" name="send_to" value="'.$form_state['values']['phone_list'].'" size="60" maxlength="128" class="form-text required">
      <div class="description">fax #. where to send fax</div>
    </div>';
    //$animal = 'hello world';
    $output[] = ajax_command_html('.form-item-send-to', $animal);
    $output[] = ctools_modal_command_dismiss(t('Login Success'));
  }
  print ajax_render($output);

}

function ictfax_list_contacts($form, &$form_state, $edit = array()) {
  $edit += array(
    'table'      => '',
    'phone_list' => '',
  );
  global $user;
  
  $header = array(
    'first_name'   => t('First Name'),
    'last_name'    => t('Last Name'),
    'phone'        => t('phone'),
    'email'        => t('E-Mail'),
  );

  $query = CoreDB::db_select('contact', 'c')->extend('PagerDefault');
  $query->fields('c', array('contact_id', 'first_name','last_name', 'phone', 'email'));
  $query->condition('c.created_by', $user->uid,'=');
  $result = $query->limit(10)
            ->extend('TableSort')
            ->orderByHeader($header)
            ->execute();

  $options = array();
  while ($contact = $result->fetchAssoc()) {
    $options[$contact['contact_id']] = array(
      'first_name' => check_plain($contact['first_name']),
      'last_name'  => check_plain($contact['last_name']),
      'phone'      => check_plain($contact['phone']),
      'email'      => check_plain($contact['email']),
    );
  }

  $form['info']['table'] = array(
    '#type'     => 'tableselect',
    '#header'   => $header,
    '#options'  => $options,
    '#multiple' => FALSE,
//    '#input'=>true,
    '#empty' => t('No record available'),
//    '#advanced_select'=>false,
    '#attributes' => '',
//    '#default_value'=> $edit['table'],
  );

  $form['info']['pager'] = array(
    '#type'   => 'item',
    '#markup' => theme('pager'),
  );
  
  $form['phone_list'] = array(
    '#type' => 'hidden',
//    '#value' => $edit['phone_list'],
  );

  $form['info']['submit'] = array(
    '#type'  => 'submit',
    '#value' => t('Select'),
  );

  return $form;
}

function ictfax_list_contacts_submit($form, &$form_state) {
  $contacts = $form_state['values'];
  $phone = array();
  $id = $contacts['table'];
  if($id > 0) {
    $sql    = "SELECT phone FROM contact WHERE contact_id =:contact_id";
    $result = CoreDB::db_query($sql, array(':contact_id' => $id))->fetchAssoc();
    //$phone[] = $result['phone'];
    $phone = $result['phone'];
  }
  //$phone = implode($phone, ',');
  $form_state['values']['phone_list'] = $phone;
  $form_state['complete'] = TRUE; 
}
?>
